pure.upLoadPath: File

server:
  port: 80
  servlet:
    context-path: /

spring:
  application:
    name: module1
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql:///mybatis?characterEncoding=utf-8&useSSL=false&useUnicode=true&autoReconnect=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    date-format:   yyyy-MM-dd HH:mm:ss
    time-zone:   GMT+8
  aop:
    proxy-target-class: true

logging:
  level:
    com.lyf.mapper: trace

mybatis-plus:
  check-config-location: